apiVersion: v1
kind: ConfigMap
metadata:
  name: msa-k8s-configmap
data:
  gateway_ip: "192.168.65.3"
  token_expiration_time: "86400000"
  token_secret: "k8s-default-jwt-token-secret-value"
  order-service-url: "http://order-service:10000"
  bootstrap-servers: "192.168.65.3:9092"