server:
  port: 8761

spring:
  application:
    name: eureka-server

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false

---
server:
  port: 8762

spring:
  config:
    activate:
      on-profile: eureka2
eureka:
  client:
    service-url:
      defaultZone: http://duckbill413-gb4:8763/eureka
  instance:
    hostname: localhost

---
server:
  port: 8763

spring:
  config:
    activate:
      on-profile: eureka3

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8762/eureka
  instance:
    hostname: duckbill413-gb4.local