token:
  expiration_time: 86400000
#  secret: "LOCAL-AQqafoiasFwfaKOwFSnpionvpiagq41Ine"
  secret: "{cipher}AQA8mjdd8mS7YX3EAT25hewh0F4TbCy2x53NF/rueo0g4/J9uHh+V82yRBEwYl6Ej5tc/Z4UhVZIUBAQX59eBUxvChKxDHOGt1yuNFQbj8v/yn1KAgp+cHkKPH7u7DgHwK1WIvYQuHM5N2Eq3YXxNG0puWd+Qflfwt5leaIzUytIW3oNMI84YAtadxlbKm909aWwXk8KjyzzyX/HhohZYCKu1AY82g+Rm8TqWOGmOK7eYhkdmc3vx5VIj/iaSDxLwAGEHSpAFPxlpZDnVvycjDAUMcSc3ESQOZus2cL2trjzWRVpBeXClSgwwcTL/FuLC5UUxfa3JJ/Hguj1rUNm8aTl2U7S7VSW3VHexHnVVWh22OsnyGN8Oxl6rCyniIQ8o2g7SdFR9uSxdEojC6E8vOzbPLzC4IyZ9sGlBa03Xm8ydrZ5xcX3/orKffyyCmjSCm4WFFhpuTAURTAwXgq41Ine"

gateway:
  ip: 172.18.0.5
