server:
  port: 8888

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: file://D:/git/spring-cloud-microservice
          default-label: master